// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-KsaqZyIve8kCDN3Cz10cz-sc9EaS6Eg',
    appId: '1:5521801664:web:d4eca68d3977ad0327c825',
    messagingSenderId: '5521801664',
    projectId: 'gratitude-garden-3991c',
    authDomain: 'gratitude-garden-3991c.firebaseapp.com',
    storageBucket: 'gratitude-garden-3991c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtcYruDKSEWCgR0lWTVM2PfZWNeLNDDAY',
    appId: '1:5521801664:android:28c908886a29ea9327c825',
    messagingSenderId: '5521801664',
    projectId: 'gratitude-garden-3991c',
    storageBucket: 'gratitude-garden-3991c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBochzCprTeSUBW03IYeob_pFOS2Wtm4MM',
    appId: '1:5521801664:ios:22f99af7198a245927c825',
    messagingSenderId: '5521801664',
    projectId: 'gratitude-garden-3991c',
    storageBucket: 'gratitude-garden-3991c.firebasestorage.app',
    iosBundleId: 'com.example.gratitudeGardenApp',
  );
}
